project:
  type: website

website:
  title: "CSPP LIBRARY"
  favicon: images/favicon-logo.png
  back-to-top-navigation: true
  navbar:
    logo: images/favicon-logo.png
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: inventory.qmd
        text: Books at the CSPP  
    tools:
      - icon: instagram
        href: https://www.instagram.com/cspplibrary/

format:
  html:
    theme: [cosmo, custom.scss]
    toc: true
    smooth-scroll: true



